In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.7.0+cpu


## Introduction to Tensors



## scalar


In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
print(f"Dimensiones de escalar: {scalar.ndim}")
print(f"Shape del escalar {scalar.shape}")

Dimensiones de escalar: 0
Shape del escalar torch.Size([])


## Vector 

In [5]:
vector = torch.tensor([1,2])

In [6]:
print(f"Dimensiones del vector {vector.ndim}")
print(f"Forma del vector {vector.shape}")

Dimensiones del vector 1
Forma del vector torch.Size([2])


## Matriz


In [7]:
matriz = torch.tensor([[1,2],
                       [3,4]])

In [8]:
print(f"Dimensiones de la matriz {matriz.ndim}")
print(f"Forma de la matriz {matriz.shape}")

Dimensiones de la matriz 2
Forma de la matriz torch.Size([2, 2])


## Tensor

In [9]:
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]],
                       
                       [[1,2,3],
                       [4,5,6],
                       [7,8,9]]])


In [10]:
print(f"Dimensiones del tensor: {tensor.ndim}")
print(f"Shape of the tensor {tensor.shape}")

Dimensiones del tensor: 3
Shape of the tensor torch.Size([2, 3, 3])


In [11]:
torch.randn(2,3,4)

tensor([[[ 0.8472, -1.2931,  1.3315,  0.0415],
         [-2.3026, -1.9313,  2.4657, -1.6281],
         [ 0.9068, -1.3708, -0.3513, -0.8588]],

        [[-0.8284,  2.1416, -0.0397, -0.0787],
         [-1.1838, -0.6111,  0.8862, -0.8805],
         [ 0.1327,  2.7693,  0.8068,  0.4430]]])

In [12]:
random_image_size = torch.rand(size=(3,224,224)) # channel, height, width
random_image_size.shape, random_image_size.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and Ones

In [13]:
# tensor of all zeros 

zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
ones = torch.ones(size=(2,3,4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

## Creating a range of tensors and tensors-like

In [15]:
# use torch.arange()

arange_example=torch.arange(0,10) # start, end, step we can also use start,end 
arange_example

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
ten_zeros = torch.zeros_like(input=arange_example)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
ten_ones = torch.ones_like(input=arange_example)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor datatypes

In [ ]:
# float 32 tensor

float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               device=None, #what device is your tensor on
                               dtype=None,   #what dtypes is the tensor 
                               requires_grad=False) #wheter or not to track gradients

# default dtype in pytorch will be float_32

float_32_tensor.dtype


'''
dtypes can be:
torch.float32
torch.float64
torch.float16

url https://docs.pytorch.org/docs/stable/tensors.html

'''

'\ndtypes can be:\ntorch.float32\ntorch.float64\ntorch.float16\n\nurl https://docs.pytorch.org/docs/stable/tensors.html\n\n'

## Operations with Tensor

In [19]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [20]:
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [21]:
tensor = torch.tensor([1,2,3])
tensor - 10

tensor([-9, -8, -7])

In [22]:
tensor = torch.tensor([1,2,3])
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [23]:
## pytorch in-built functions 

torch.mul(tensor,10)

tensor([10, 20, 30])

In [24]:
torch.add(tensor, 10)

tensor([11, 12, 13])

## Matrix multiplication  

dot product

In [25]:
a = torch.tensor( [[2,1,3], 
                 [3,2,1],
                 [1,2,3]])


print (f"A shape {a.shape}")
print (f"A dimension {a.ndim}")

A shape torch.Size([3, 3])
A dimension 2


In [26]:
b = torch.tensor([[3,1],
                  [2,2],
                  [1,3]
])

print (f"b shape {b.shape}")
print (f"b dimension {b.ndim}")

b shape torch.Size([3, 2])
b dimension 2


In [27]:
a @ b

tensor([[11, 13],
        [14, 10],
        [10, 14]])

In [28]:
torch.matmul(a,b)

tensor([[11, 13],
        [14, 10],
        [10, 14]])

In [29]:

random_matrix_1 = torch.rand(size=(3,3))
random_matrix_2 = torch.rand(size=(3,2))

print(random_matrix_1)
print(random_matrix_2)

tensor([[0.3232, 0.0943, 0.3994],
        [0.0376, 0.1399, 0.3525],
        [0.3053, 0.7174, 0.5528]])
tensor([[0.5712, 0.6217],
        [0.6970, 0.5794],
        [0.6652, 0.4657]])


In [30]:
random_matrix_1 @ random_matrix_2

tensor([[0.5160, 0.4416],
        [0.3535, 0.2686],
        [1.0422, 0.8629]])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [31]:
x = torch.arange(0,10,1)


In [35]:
x.min(), torch.min(x)

(tensor(0), tensor(0))

In [36]:
torch.max(x), x.max()

(tensor(9), tensor(9))

In [38]:
torch.mean(x.type(torch.float32))

tensor(4.5000)

In [39]:
(x.type(torch.float32)).mean()

tensor(4.5000)

In [42]:
x = x.type(torch.float32)

In [43]:
x.dtype

torch.float32

## Finding the positional min and max 

In [44]:
x = torch.tensor([1,2,3])

In [47]:
x.min(), x.argmin()

(tensor(1), tensor(0))

In [48]:
x.max(), x.argmax()

(tensor(3), tensor(2))

## Reshaping, Viewing and Stacking Tensors

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
## Add an extra dimension 

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [51]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory)

z[:, 0] = 5 # esta forma se le asigna a la primera columna cuando se maneja más de una dimensión
x, z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
a = torch.tensor([1,2])
b = torch.tensor([3,4])
c = torch.tensor([5,6])

stacked = torch.stack([a,b,c], dim=1)
stacked 

tensor([[1, 3, 5],
        [2, 4, 6]])

## Squeeze

In [75]:
x = torch.randn(1,3,1,5)
x, x.shape

(tensor([[[[-1.2567,  0.8054,  1.0253,  0.7135,  3.1901]],
 
          [[-0.6466, -1.0492, -0.3329,  1.1909, -1.2430]],
 
          [[ 1.1519,  0.4672,  0.3810,  1.0360, -1.9655]]]]),
 torch.Size([1, 3, 1, 5]))

## Unsqueeze

In [82]:
x = torch.randn(8, 3, 224, 224)  # 8 imagenes, 3 canales RGB, altura 224 y ancho 224

x.shape, x.ndim
x


tensor([[[[ 1.5436, -1.3762,  0.9801,  ...,  0.8147,  0.9180,  0.9611],
          [-1.8107,  0.0194,  0.9909,  ..., -0.4079, -0.3646,  0.2175],
          [-0.7596, -0.3981,  0.2648,  ...,  0.7089, -0.9009, -0.6504],
          ...,
          [-0.6169,  0.6206,  1.8934,  ..., -0.1171, -0.4378, -0.4405],
          [ 1.1256,  0.7754, -0.6325,  ..., -0.8075, -0.9087,  2.1423],
          [-1.6449,  0.6153,  0.1792,  ..., -0.9005,  1.5037,  0.2654]],

         [[ 0.2052, -0.9857, -0.3203,  ...,  1.3243, -0.9363, -0.0188],
          [ 1.3283,  1.3689,  0.2997,  ...,  0.2529, -1.4447, -1.0199],
          [ 0.7104, -0.5981, -0.3798,  ...,  0.6036,  2.2104, -0.5680],
          ...,
          [ 0.3733,  0.2632, -1.0970,  ..., -0.4564,  0.4260,  0.1347],
          [ 1.0123, -0.0534, -0.1442,  ..., -0.0599,  0.1149, -1.4942],
          [-0.5105, -0.0121,  1.7445,  ...,  0.7968, -0.4885, -0.5861]],

         [[ 2.7598, -1.3077, -1.4178,  ...,  0.9039,  0.7630,  0.2875],
          [ 0.5712,  0.3606, -

In [81]:
x_unsqueezed = torch.unsqueeze(x, dim=0)
x_unsqueezed

tensor([[[[[ 1.6515e+00,  5.2583e-01, -1.0856e+00,  ...,  1.4521e+00,
            -1.2936e+00,  4.8939e-02],
           [ 5.5676e-01,  4.1821e-01, -6.9558e-01,  ..., -7.4968e-01,
            -2.3875e-01, -1.0340e+00],
           [ 8.8611e-02, -5.9146e-01,  1.3547e+00,  ..., -5.1489e-01,
            -1.0878e+00,  1.0638e+00],
           ...,
           [ 8.2170e-01, -1.3537e+00, -5.2290e-01,  ...,  1.1335e+00,
            -1.8969e-02, -1.2171e+00],
           [-2.5735e-01,  2.2823e-01,  6.1198e-01,  ..., -2.6455e-01,
            -9.1726e-01, -2.2430e+00],
           [-2.2391e+00, -2.0590e+00,  8.8304e-01,  ...,  9.9051e-01,
            -1.5381e+00,  1.1579e+00]],

          [[ 7.8289e-01,  1.3907e+00, -4.6769e-01,  ...,  1.5008e+00,
             1.8868e-01, -6.9243e-01],
           [-2.0142e-01,  8.6788e-01, -9.8780e-01,  ...,  1.2447e-01,
             1.7795e+00, -2.7426e-01],
           [-2.9970e-01,  6.1366e-01, -3.3888e-01,  ..., -1.3121e+00,
            -2.1919e-01, -4.3899e-01],
 

## Permute

No cambia los valores, solo cambia el orden de las dimensiones

In [83]:
x = torch.randn(2,3,4)

x_perm = x.permute(1,0,2) # la dim 0 pasó a la posición 1, la dim 1 pasó a la 0, la dim 2 se quedó en la posición 2

## Selecting Data From Tensors (Indexing)

In [110]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [111]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [112]:
x[0][0]

tensor([1, 2, 3])

In [113]:
x[0][0][1]

tensor(2)

In [107]:
x = torch.arange(1,10).reshape(3,3)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [108]:
x[0]

tensor([1, 2, 3])

In [109]:
# We can use ":" to select "all" of a target dimension

x[:, 1]

tensor([2, 5, 8])

## PyTorch tensors & Numpy

Pytorch has functionality to interact with it 

- Numpy -> PyTorch tensor = torch.from_numpy(ndarray)
- Pytorch tensor -> NumPy = torch.Tensor.numpy()

In [119]:
import torch 
import numpy as np 

array = np.arange(1, 8)

tensor = torch.from_numpy(array)

array, tensor

(array([1, 2, 3, 4, 5, 6, 7]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [120]:
array.dtype, tensor.dtype

(dtype('int64'), torch.int64)

In [124]:
# Change 
tensor = torch.ones(5)
numpy_tensor = tensor.numpy()

tensor, numpy_tensor

tensor = tensor + 1
tensor, numpy_tensor



(tensor([2., 2., 2., 2., 2.]), array([1., 1., 1., 1., 1.], dtype=float32))

## Pytorch Reproducibility 

start with random numbers -> tensor operations -> update random numbers to try and make them representation of the data -> again -> again -> again


In [125]:
torch.rand(3,3)

tensor([[0.3052, 0.1948, 0.1291],
        [0.6311, 0.3623, 0.5322],
        [0.1499, 0.8919, 0.9665]])

In [127]:
random_tensor_a = torch.rand(3,3)
random_tensor_b = torch.rand(3,3)

print(random_tensor_a)
print(random_tensor_b)

print(random_tensor_a == random_tensor_b)

tensor([[0.0080, 0.2107, 0.8242],
        [0.1077, 0.4957, 0.9806],
        [0.6326, 0.3647, 0.5155]])
tensor([[0.2656, 0.4112, 0.1521],
        [0.1855, 0.7019, 0.4381],
        [0.1862, 0.9297, 0.9581]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [129]:
random_seed = 42
torch.manual_seed(random_seed)

random_tensor_r = torch.rand(3,3)

torch.manual_seed(random_seed)

random_tensor_d = torch.rand(3,3)

print(random_tensor_r == random_tensor_d)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


## PyTorch objects on the GPUs

In [133]:
device = "cuda" if torch.cuda.is_available() else "cpu"


In [134]:
torch.cuda.device_count()

0

In [135]:
tensor = torch.tensor([1,2,3],
                      device=device)

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [137]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu   

tensor([1, 2, 3])