URL: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
!pip install torch

Defaulting to user installation because normal site-packages is not writeable


In [2]:
import torch
torch.__version__

'2.5.1+cu121'

In [3]:
scalar = torch.tensor(7)
scalar, scalar.item(), float(scalar), int(scalar), scalar.ndim, scalar.shape, scalar.size()

(tensor(7), 7, 7.0, 7, 0, torch.Size([]), torch.Size([]))

In [4]:
vector = torch.tensor([7, 7, 7])
vector, vector.ndim, vector.shape, vector.size()

(tensor([7, 7, 7]), 1, torch.Size([3]), torch.Size([3]))

In [5]:
MATRIX = torch.tensor([[7, 8],[9, 10]])
MATRIX, MATRIX.ndim, MATRIX.shape, MATRIX.size()

(tensor([[ 7,  8],
         [ 9, 10]]),
 2,
 torch.Size([2, 2]),
 torch.Size([2, 2]))

In [6]:
TENSOR = torch.tensor([[[1, 2, 3],[4,5,6]],[[7,8,9],[10,11,12]]])
TENSOR, TENSOR.ndim, TENSOR.shape, TENSOR.size()

(tensor([[[ 1,  2,  3],
          [ 4,  5,  6]],
 
         [[ 7,  8,  9],
          [10, 11, 12]]]),
 3,
 torch.Size([2, 2, 3]),
 torch.Size([2, 2, 3]))

In [7]:
random_tensor = torch.rand(3, 4)
random_tensor, random_tensor.ndim, random_tensor.shape, random_tensor.size()

(tensor([[0.8477, 0.0542, 0.9645, 0.5200],
         [0.1874, 0.0743, 0.9596, 0.7662],
         [0.4075, 0.9133, 0.2148, 0.1425]]),
 2,
 torch.Size([3, 4]),
 torch.Size([3, 4]))

In [8]:
random_tensor = torch.rand(3, 244, 244)
random_tensor, random_tensor.ndim, random_tensor.shape, random_tensor.size()

(tensor([[[0.7277, 0.7961, 0.0438,  ..., 0.0189, 0.4487, 0.1520],
          [0.9981, 0.9154, 0.5383,  ..., 0.5645, 0.3612, 0.3723],
          [0.3763, 0.5889, 0.6048,  ..., 0.1964, 0.1577, 0.8965],
          ...,
          [0.1267, 0.9642, 0.6853,  ..., 0.0509, 0.5155, 0.8330],
          [0.7898, 0.7300, 0.9335,  ..., 0.3336, 0.0659, 0.9569],
          [0.0338, 0.0170, 0.8084,  ..., 0.0677, 0.2668, 0.6073]],
 
         [[0.0844, 0.4090, 0.3912,  ..., 0.6099, 0.2449, 0.7193],
          [0.4287, 0.8854, 0.4987,  ..., 0.3452, 0.7639, 0.4660],
          [0.6272, 0.0441, 0.0077,  ..., 0.1846, 0.8730, 0.4581],
          ...,
          [0.9006, 0.7233, 0.0696,  ..., 0.0238, 0.9814, 0.1217],
          [0.9890, 0.1564, 0.5085,  ..., 0.3420, 0.3392, 0.2743],
          [0.9242, 0.8122, 0.2769,  ..., 0.8467, 0.7844, 0.0969]],
 
         [[0.9747, 0.9959, 0.6827,  ..., 0.5215, 0.1680, 0.7440],
          [0.0934, 0.1876, 0.2375,  ..., 0.6566, 0.7268, 0.8956],
          [0.1829, 0.6546, 0.5658,  ...,

In [9]:
zeros = torch.zeros(3, 4)
zeros 

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
ones = torch.ones(3, 4)
ones, ones.dtype, ones.shape, ones.ndim 

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32,
 torch.Size([3, 4]),
 2)

In [11]:
# arange (start, end, step)

zero_to_nine = torch.arange(0, 10)
zero_to_nine, zero_to_nine.ndim, zero_to_nine.shape, zero_to_nine.size()

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 1, torch.Size([10]), torch.Size([10]))

In [12]:
zero_to_nine = torch.arange(0, 10, 2)
zero_to_nine, zero_to_nine.ndim, zero_to_nine.shape, zero_to_nine.size()

(tensor([0, 2, 4, 6, 8]), 1, torch.Size([5]), torch.Size([5]))

In [13]:
five_zeros = torch.zeros_like(input=zero_to_nine)
five_zeros, five_zeros.ndim, five_zeros.shape, five_zeros.size()

(tensor([0, 0, 0, 0, 0]), 1, torch.Size([5]), torch.Size([5]))

In [14]:
float_32_tensor = torch.rand(3, 4, 
                            dtype=torch.float32, # default to None, which is torch.float32 
                            device=None, # default to None, which is CPU  
                            requires_grad=True) # if True, will track computation history
float_32_tensor 

tensor([[0.1604, 0.2318, 0.4781, 0.8701],
        [0.0951, 0.7181, 0.1584, 0.2964],
        [0.3981, 0.0800, 0.0218, 0.6989]], requires_grad=True)

In [15]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device of tensor: {some_tensor.device}")


tensor([[0.8333, 0.7287, 0.1167, 0.2351],
        [0.8611, 0.6917, 0.9787, 0.8692],
        [0.5438, 0.1440, 0.4546, 0.3689]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device of tensor: cpu


## Tensor operations

In [16]:
tensor = torch.tensor([1, 2, 3])
sum_tensor = tensor + 10
res_tensor = tensor - 10
mul_tensor = tensor * 10

sum_tensor, res_tensor, mul_tensor

(tensor([11, 12, 13]), tensor([-9, -8, -7]), tensor([10, 20, 30]))

In [17]:
# element-wise multiplication
tensor * tensor


tensor([1, 4, 9])

In [18]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [19]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## Agreggation 

In [20]:
x = torch.arange(0,100,10)
print(f"X: {x}")

print(f"Mayor valor: {x.max()}")
print(f"Menor valor: {x.min()}")

print(f"Posicion mayor valor: {x.argmax()}" )
print(f"Posicion menor valor: {x.argmin()}")

X: tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
Mayor valor: 90
Menor valor: 0
Posicion mayor valor: 9
Posicion menor valor: 0


In [21]:
x = x.type(torch.float16) # cambiamos el tipo de dato

## Method	One-line description


- torch.reshape(input, shape)	Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
- Tensor.view(shape)	Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
- torch.stack(tensors, dim=0)	Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
- torch.squeeze(input)	Squeezes input to remove all the dimenions with value 1.
- torch.unsqueeze(input, dim)	Returns input with a dimension value of 1 added at dim.
- torch.permute(input, dims)	Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [22]:
x = torch.arange(1,8)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7]), torch.Size([7]))

In [23]:
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7]]), torch.Size([1, 7]))

In [24]:
x_stacked = torch.stack([x_reshaped, x_reshaped])
x_stacked, x_stacked.shape

(tensor([[[1, 2, 3, 4, 5, 6, 7]],
 
         [[1, 2, 3, 4, 5, 6, 7]]]),
 torch.Size([2, 1, 7]))

In [25]:
print(f"previous tensor: {x_reshaped}")
print(f"Prevous tensor shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()

print(f"New tensor: {x_squeezed}")
print(f"New tensor shape: {x_squeezed.shape}")

previous tensor: tensor([[1, 2, 3, 4, 5, 6, 7]])
Prevous tensor shape: torch.Size([1, 7])
New tensor: tensor([1, 2, 3, 4, 5, 6, 7])
New tensor shape: torch.Size([7])


In [26]:
x_new = torch.rand(224,224,3)
print(f"Old shape: {x_new.shape}")


x_permuted = x_new.permute(2,1,0)
print(f"New shape: {x_permuted.shape}")
x_permuted


Old shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


tensor([[[0.6036, 0.4674, 0.9657,  ..., 0.6585, 0.1593, 0.7220],
         [0.9916, 0.5730, 0.0378,  ..., 0.3658, 0.8766, 0.7687],
         [0.1980, 0.9701, 0.6010,  ..., 0.8451, 0.8044, 0.7816],
         ...,
         [0.9300, 0.9190, 0.8676,  ..., 0.3350, 0.2751, 0.9298],
         [0.3347, 0.9494, 0.8670,  ..., 0.4494, 0.6755, 0.9540],
         [0.3291, 0.2110, 0.2510,  ..., 0.5698, 0.4673, 0.1677]],

        [[0.6480, 0.1243, 0.7743,  ..., 0.4913, 0.3485, 0.2655],
         [0.4759, 0.2529, 0.3946,  ..., 0.6692, 0.4376, 0.3717],
         [0.8586, 0.1157, 0.6043,  ..., 0.8702, 0.8101, 0.8629],
         ...,
         [0.4570, 0.2923, 0.4461,  ..., 0.2502, 0.6251, 0.2534],
         [0.6768, 0.4357, 0.2640,  ..., 0.8707, 0.6104, 0.7367],
         [0.8538, 0.3192, 0.6809,  ..., 0.3685, 0.7292, 0.6111]],

        [[0.5098, 0.4786, 0.0301,  ..., 0.5649, 0.0858, 0.3755],
         [0.9119, 0.6836, 0.1836,  ..., 0.3972, 0.0502, 0.1015],
         [0.7582, 0.5953, 0.7291,  ..., 0.6419, 0.3560, 0.

## Indexing (Selecting data from tensors)


In [38]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape, x.ndim

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]),
 3)

In [37]:
# indexing values foes outer dimensions to inner dimensions
print(f"First square bracket: \n {x[0]}")
print(f"Second square bracket: \n {x[0][1]}")
print(f"Third square bracket: \n {x[0][0][1]}")

First square bracket: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: 
 tensor([4, 5, 6])
Third square bracket: 
 2


In [ ]:
# get all vallues of the 0th dimension and the 0 index of 1st dimension
x[:,0]

tensor([[1, 2, 3]])

In [41]:
x[0,0]

tensor([1, 2, 3])

## Pytorch tensors & Numpy 

In [44]:
import torch
import numpy as np 

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [46]:
x = x.type(torch.float16) # cambiamos el tipo de dato
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))